# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: the_abyss_left nice_view
  - board: nice_nano_v2
    shield: the_abyss_right nice_view

#                 KEY POSITIONS
#
# ╭────────────────────╮ ╭────────────────────╮
# │  0   1   2   3   4 │ │  5   6   7   8   9 │
# │ 10  11  12  13  14 │ │ 15  16  17  18  19 │
# │ 20  21  22  23  24 │ │ 25  26  27  28  29 │
# ╰───────╮ 30  31  32 │ │ 33  34  35 ╭───────╯
#         ╰────────────╯ ╰────────────╯
