# Eager debounce for presses
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=2
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=4

# Allow 3 Bluetooth connections
CONFIG_BT_MAX_CONN=3
CONFIG_BT_MAX_PAIRED=3

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
